seed: 3407
num_workers: 4 # mp.cpu_count() = 8
total_steps: 200000 # 200 * 1000 = 200000
update_steps: 50 # update frequency
test_episodes: 100
max_steps: 200 # default: 200
lr: .0001
gamma: .99
beta: .01
lambda: 1.
value_coef: 1
max_grad_norm: 50.
render: True
# render: False
g: 10.
noise_std: .005
models_path: "./modelset/a3c/a3c"
images_path: "./images/a3c/"
