seed: 3407
num_episodes: 1000 # 1000 for Ant, 3000 for Hopper
test_episodes: 100
num_epochs: 2
warmup_steps: 100 # need to be greater than batch_size
max_steps: 1000 # default: 1000
lr: .0001
gamma: .9
tau: .01
batch_size: 64
memory_size: 1000000
render: True
# render: False
noise_std: .005
