seed: 3407
num_episodes: 3000 # 500 for pong, 3000 for boxing
test_episodes: 100
num_epochs: 1
warmup_steps: 100 # need to be greater than batch_size
max_steps: 1000 # default: 1000
lr: .0001
gamma: .9
epsilon_min: .01
epsilon_decay: .995
batch_size: 64
memory_size: 1000000
render: True
# render: False
target_update: 100
target_h: 84
target_w: 84
# grayscale: True
